/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
Traceback (most recent call last):
  File "/home/guo/mmix/odernn/main.py", line 6, in <module>
    import utils
  File "/home/guo/mmix/odernn/utils.py", line 8, in <module>
    import pandas as pd
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/pandas/core/arrays/arrow/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/pandas/core/arrays/arrow/array.py", line 54, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1349, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1321, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1477, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1435, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 636, in spec_from_file_location
KeyboardInterrupt
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
Traceback (most recent call last):
  File "/home/guo/mmix/odernn/main.py", line 124, in <module>
    run()
  File "/home/guo/mmix/odernn/main.py", line 119, in run
    train(model)
  File "/home/guo/mmix/odernn/main.py", line 70, in train
    ret = model.run_on_batch(data, optimizer, epoch)
  File "/home/guo/mmix/odernn/models/brits.py", line 66, in run_on_batch
    ret = self(data, mode="train")
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/brits.py", line 24, in forward
    ret_f = self.rits_f(data, 'forward', mode)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/rits.py", line 51, in forward
    outputs = self.ode_rnn(inputs, m, m_first, time_steps)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/ode_rnn.py", line 202, in forward
    hidden = mask_first[:, i - 1] * hidden
RuntimeError: The size of tensor a (325) must match the size of tensor b (170) at non-singleton dimension 1
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
Traceback (most recent call last):
  File "/home/guo/mmix/odernn/main.py", line 124, in <module>
    run()
  File "/home/guo/mmix/odernn/main.py", line 119, in run
    train(model)
  File "/home/guo/mmix/odernn/main.py", line 70, in train
    ret = model.run_on_batch(data, optimizer, epoch)
  File "/home/guo/mmix/odernn/models/brits.py", line 66, in run_on_batch
    ret = self(data, mode="train")
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/brits.py", line 24, in forward
    ret_f = self.rits_f(data, 'forward', mode)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/rits.py", line 51, in forward
    outputs = self.ode_rnn(inputs, m, m_first, time_steps)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/ode_rnn.py", line 202, in forward
    hidden = mask_first[:, i - 1] * hidden
RuntimeError: The size of tensor a (323) must match the size of tensor b (170) at non-singleton dimension 1
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
Traceback (most recent call last):
  File "/home/guo/mmix/odernn/main.py", line 124, in <module>
    run()
  File "/home/guo/mmix/odernn/main.py", line 119, in run
    train(model)
  File "/home/guo/mmix/odernn/main.py", line 70, in train
    ret = model.run_on_batch(data, optimizer, epoch)
  File "/home/guo/mmix/odernn/models/brits.py", line 66, in run_on_batch
    ret = self(data, mode="train")
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/brits.py", line 24, in forward
    ret_f = self.rits_f(data, 'forward', mode)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/rits.py", line 51, in forward
    outputs = self.ode_rnn(inputs, m, m_first, time_steps)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/ode_rnn.py", line 202, in forward
    hidden = mask_first[:, i - 1] * hidden
RuntimeError: The size of tensor a (325) must match the size of tensor b (170) at non-singleton dimension 1
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
Traceback (most recent call last):
  File "/home/guo/mmix/odernn/main.py", line 124, in <module>
    run()
  File "/home/guo/mmix/odernn/main.py", line 119, in run
    train(model)
  File "/home/guo/mmix/odernn/main.py", line 70, in train
    ret = model.run_on_batch(data, optimizer, epoch)
  File "/home/guo/mmix/odernn/models/brits.py", line 66, in run_on_batch
    ret = self(data, mode="train")
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/brits.py", line 24, in forward
    ret_f = self.rits_f(data, 'forward', mode)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/rits.py", line 51, in forward
    outputs = self.ode_rnn(inputs, m, m_first, time_steps)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/ode_rnn.py", line 202, in forward
    hidden = mask_first[:, i - 1] * hidden
RuntimeError: The size of tensor a (323) must match the size of tensor b (170) at non-singleton dimension 1
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
Traceback (most recent call last):
  File "/home/guo/mmix/odernn/main.py", line 124, in <module>
    run()
  File "/home/guo/mmix/odernn/main.py", line 119, in run
    train(model)
  File "/home/guo/mmix/odernn/main.py", line 70, in train
    ret = model.run_on_batch(data, optimizer, epoch)
  File "/home/guo/mmix/odernn/models/brits.py", line 66, in run_on_batch
    ret = self(data, mode="train")
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/brits.py", line 24, in forward
    ret_f = self.rits_f(data, 'forward', mode)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/rits.py", line 51, in forward
    outputs = self.ode_rnn(inputs, m, m_first, time_steps)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/ode_rnn.py", line 202, in forward
    hidden = mask_first[:, i - 1] * hidden
RuntimeError: The size of tensor a (325) must match the size of tensor b (170) at non-singleton dimension 1
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
Traceback (most recent call last):
  File "/home/guo/mmix/odernn/main.py", line 124, in <module>
    run()
  File "/home/guo/mmix/odernn/main.py", line 119, in run
    train(model)
  File "/home/guo/mmix/odernn/main.py", line 70, in train
    ret = model.run_on_batch(data, optimizer, epoch)
  File "/home/guo/mmix/odernn/models/brits.py", line 66, in run_on_batch
    ret = self(data, mode="train")
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/brits.py", line 24, in forward
    ret_f = self.rits_f(data, 'forward', mode)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/rits.py", line 51, in forward
    outputs = self.ode_rnn(inputs, m, m_first, time_steps)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/ode_rnn.py", line 202, in forward
    hidden = mask_first[:, i - 1] * hidden
RuntimeError: The size of tensor a (323) must match the size of tensor b (170) at non-singleton dimension 1
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
Traceback (most recent call last):
  File "/home/guo/mmix/odernn/main.py", line 124, in <module>
    run()
  File "/home/guo/mmix/odernn/main.py", line 119, in run
    train(model)
  File "/home/guo/mmix/odernn/main.py", line 70, in train
    ret = model.run_on_batch(data, optimizer, epoch)
  File "/home/guo/mmix/odernn/models/brits.py", line 66, in run_on_batch
    ret = self(data, mode="train")
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/brits.py", line 24, in forward
    ret_f = self.rits_f(data, 'forward', mode)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/rits.py", line 51, in forward
    outputs = self.ode_rnn(inputs, m, m_first, time_steps)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/ode_rnn.py", line 202, in forward
    hidden = mask_first[:, i - 1] * hidden
RuntimeError: The size of tensor a (325) must match the size of tensor b (170) at non-singleton dimension 1
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
Traceback (most recent call last):
  File "/home/guo/mmix/odernn/main.py", line 124, in <module>
    run()
  File "/home/guo/mmix/odernn/main.py", line 119, in run
    train(model)
  File "/home/guo/mmix/odernn/main.py", line 70, in train
    ret = model.run_on_batch(data, optimizer, epoch)
  File "/home/guo/mmix/odernn/models/brits.py", line 66, in run_on_batch
    ret = self(data, mode="train")
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/brits.py", line 24, in forward
    ret_f = self.rits_f(data, 'forward', mode)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/rits.py", line 51, in forward
    outputs = self.ode_rnn(inputs, m, m_first, time_steps)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/ode_rnn.py", line 202, in forward
    hidden = mask_first[:, i - 1] * hidden
RuntimeError: The size of tensor a (323) must match the size of tensor b (170) at non-singleton dimension 1
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
Traceback (most recent call last):
  File "/home/guo/mmix/odernn/main.py", line 124, in <module>
    run()
  File "/home/guo/mmix/odernn/main.py", line 119, in run
    train(model)
  File "/home/guo/mmix/odernn/main.py", line 70, in train
    ret = model.run_on_batch(data, optimizer, epoch)
  File "/home/guo/mmix/odernn/models/brits.py", line 66, in run_on_batch
    ret = self(data, mode="train")
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/brits.py", line 24, in forward
    ret_f = self.rits_f(data, 'forward', mode)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/rits.py", line 51, in forward
    outputs = self.ode_rnn(inputs, m, m_first, time_steps)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/ode_rnn.py", line 202, in forward
    hidden = mask_first[:, i - 1] * hidden
RuntimeError: The size of tensor a (325) must match the size of tensor b (170) at non-singleton dimension 1
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
Traceback (most recent call last):
  File "/home/guo/mmix/odernn/main.py", line 124, in <module>
    run()
  File "/home/guo/mmix/odernn/main.py", line 119, in run
    train(model)
  File "/home/guo/mmix/odernn/main.py", line 70, in train
    ret = model.run_on_batch(data, optimizer, epoch)
  File "/home/guo/mmix/odernn/models/brits.py", line 66, in run_on_batch
    ret = self(data, mode="train")
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/brits.py", line 24, in forward
    ret_f = self.rits_f(data, 'forward', mode)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/rits.py", line 51, in forward
    outputs = self.ode_rnn(inputs, m, m_first, time_steps)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/ode_rnn.py", line 202, in forward
    hidden = mask_first[:, i - 1] * hidden
RuntimeError: The size of tensor a (323) must match the size of tensor b (170) at non-singleton dimension 1
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
Traceback (most recent call last):
  File "/home/guo/mmix/odernn/main.py", line 124, in <module>
    run()
  File "/home/guo/mmix/odernn/main.py", line 119, in run
    train(model)
  File "/home/guo/mmix/odernn/main.py", line 70, in train
    ret = model.run_on_batch(data, optimizer, epoch)
  File "/home/guo/mmix/odernn/models/brits.py", line 66, in run_on_batch
    ret = self(data, mode="train")
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/brits.py", line 24, in forward
    ret_f = self.rits_f(data, 'forward', mode)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/rits.py", line 51, in forward
    outputs = self.ode_rnn(inputs, m, m_first, time_steps)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/ode_rnn.py", line 202, in forward
    hidden = mask_first[:, i - 1] * hidden
RuntimeError: The size of tensor a (325) must match the size of tensor b (170) at non-singleton dimension 1
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
Traceback (most recent call last):
  File "/home/guo/mmix/odernn/main.py", line 124, in <module>
    run()
  File "/home/guo/mmix/odernn/main.py", line 119, in run
    train(model)
  File "/home/guo/mmix/odernn/main.py", line 70, in train
    ret = model.run_on_batch(data, optimizer, epoch)
  File "/home/guo/mmix/odernn/models/brits.py", line 66, in run_on_batch
    ret = self(data, mode="train")
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/brits.py", line 24, in forward
    ret_f = self.rits_f(data, 'forward', mode)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/rits.py", line 51, in forward
    outputs = self.ode_rnn(inputs, m, m_first, time_steps)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/ode_rnn.py", line 202, in forward
    hidden = mask_first[:, i - 1] * hidden
RuntimeError: The size of tensor a (323) must match the size of tensor b (170) at non-singleton dimension 1
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
Traceback (most recent call last):
  File "/home/guo/mmix/odernn/main.py", line 124, in <module>
    run()
  File "/home/guo/mmix/odernn/main.py", line 119, in run
    train(model)
  File "/home/guo/mmix/odernn/main.py", line 70, in train
    ret = model.run_on_batch(data, optimizer, epoch)
  File "/home/guo/mmix/odernn/models/brits.py", line 66, in run_on_batch
    ret = self(data, mode="train")
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/brits.py", line 24, in forward
    ret_f = self.rits_f(data, 'forward', mode)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/rits.py", line 51, in forward
    outputs = self.ode_rnn(inputs, m, m_first, time_steps)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/ode_rnn.py", line 202, in forward
    hidden = mask_first[:, i - 1] * hidden
RuntimeError: The size of tensor a (325) must match the size of tensor b (170) at non-singleton dimension 1
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
Traceback (most recent call last):
  File "/home/guo/mmix/odernn/main.py", line 124, in <module>
    run()
  File "/home/guo/mmix/odernn/main.py", line 119, in run
    train(model)
  File "/home/guo/mmix/odernn/main.py", line 70, in train
    ret = model.run_on_batch(data, optimizer, epoch)
  File "/home/guo/mmix/odernn/models/brits.py", line 66, in run_on_batch
    ret = self(data, mode="train")
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/brits.py", line 24, in forward
    ret_f = self.rits_f(data, 'forward', mode)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/rits.py", line 51, in forward
    outputs = self.ode_rnn(inputs, m, m_first, time_steps)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/ode_rnn.py", line 202, in forward
    hidden = mask_first[:, i - 1] * hidden
RuntimeError: The size of tensor a (323) must match the size of tensor b (170) at non-singleton dimension 1
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
Traceback (most recent call last):
  File "/home/guo/mmix/odernn/main.py", line 124, in <module>
    run()
  File "/home/guo/mmix/odernn/main.py", line 119, in run
    train(model)
  File "/home/guo/mmix/odernn/main.py", line 70, in train
    ret = model.run_on_batch(data, optimizer, epoch)
  File "/home/guo/mmix/odernn/models/brits.py", line 66, in run_on_batch
    ret = self(data, mode="train")
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/brits.py", line 24, in forward
    ret_f = self.rits_f(data, 'forward', mode)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/rits.py", line 51, in forward
    outputs = self.ode_rnn(inputs, m, m_first, time_steps)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/ode_rnn.py", line 202, in forward
    hidden = mask_first[:, i - 1] * hidden
RuntimeError: The size of tensor a (325) must match the size of tensor b (170) at non-singleton dimension 1
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
Traceback (most recent call last):
  File "/home/guo/mmix/odernn/main.py", line 124, in <module>
    run()
  File "/home/guo/mmix/odernn/main.py", line 119, in run
    train(model)
  File "/home/guo/mmix/odernn/main.py", line 70, in train
    ret = model.run_on_batch(data, optimizer, epoch)
  File "/home/guo/mmix/odernn/models/brits.py", line 66, in run_on_batch
    ret = self(data, mode="train")
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/brits.py", line 24, in forward
    ret_f = self.rits_f(data, 'forward', mode)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/rits.py", line 51, in forward
    outputs = self.ode_rnn(inputs, m, m_first, time_steps)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/ode_rnn.py", line 202, in forward
    hidden = mask_first[:, i - 1] * hidden
RuntimeError: The size of tensor a (325) must match the size of tensor b (170) at non-singleton dimension 1
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
Traceback (most recent call last):
  File "/home/guo/mmix/odernn/main.py", line 124, in <module>
    run()
  File "/home/guo/mmix/odernn/main.py", line 119, in run
    train(model)
  File "/home/guo/mmix/odernn/main.py", line 70, in train
    ret = model.run_on_batch(data, optimizer, epoch)
  File "/home/guo/mmix/odernn/models/brits.py", line 66, in run_on_batch
    ret = self(data, mode="train")
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/brits.py", line 24, in forward
    ret_f = self.rits_f(data, 'forward', mode)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/rits.py", line 51, in forward
    outputs = self.ode_rnn(inputs, m, m_first, time_steps)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/ode_rnn.py", line 202, in forward
    hidden = mask_first[:, i - 1] * hidden
RuntimeError: The size of tensor a (323) must match the size of tensor b (170) at non-singleton dimension 1
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
Traceback (most recent call last):
  File "/home/guo/mmix/odernn/main.py", line 124, in <module>
    run()
  File "/home/guo/mmix/odernn/main.py", line 119, in run
    train(model)
  File "/home/guo/mmix/odernn/main.py", line 70, in train
    ret = model.run_on_batch(data, optimizer, epoch)
  File "/home/guo/mmix/odernn/models/brits.py", line 66, in run_on_batch
    ret = self(data, mode="train")
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/brits.py", line 24, in forward
    ret_f = self.rits_f(data, 'forward', mode)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/rits.py", line 51, in forward
    outputs = self.ode_rnn(inputs, m, m_first, time_steps)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/ode_rnn.py", line 202, in forward
    hidden = mask_first[:, i - 1] * hidden
RuntimeError: The size of tensor a (323) must match the size of tensor b (170) at non-singleton dimension 1
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
Traceback (most recent call last):
  File "/home/guo/mmix/odernn/main.py", line 124, in <module>
    run()
  File "/home/guo/mmix/odernn/main.py", line 119, in run
    train(model)
  File "/home/guo/mmix/odernn/main.py", line 70, in train
    ret = model.run_on_batch(data, optimizer, epoch)
  File "/home/guo/mmix/odernn/models/brits.py", line 66, in run_on_batch
    ret = self(data, mode="train")
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/brits.py", line 24, in forward
    ret_f = self.rits_f(data, 'forward', mode)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/rits.py", line 51, in forward
    outputs = self.ode_rnn(inputs, m, m_first, time_steps)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/ode_rnn.py", line 202, in forward
    hidden = mask_first[:, i - 1] * hidden
RuntimeError: The size of tensor a (325) must match the size of tensor b (170) at non-singleton dimension 1
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
Traceback (most recent call last):
  File "/home/guo/mmix/odernn/main.py", line 124, in <module>
    run()
  File "/home/guo/mmix/odernn/main.py", line 119, in run
    train(model)
  File "/home/guo/mmix/odernn/main.py", line 70, in train
    ret = model.run_on_batch(data, optimizer, epoch)
  File "/home/guo/mmix/odernn/models/brits.py", line 66, in run_on_batch
    ret = self(data, mode="train")
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/brits.py", line 24, in forward
    ret_f = self.rits_f(data, 'forward', mode)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/rits.py", line 51, in forward
    outputs = self.ode_rnn(inputs, m, m_first, time_steps)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/ode_rnn.py", line 202, in forward
    hidden = mask_first[:, i - 1] * hidden
RuntimeError: The size of tensor a (323) must match the size of tensor b (170) at non-singleton dimension 1
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
Traceback (most recent call last):
  File "/home/guo/mmix/odernn/main.py", line 124, in <module>
    run()
  File "/home/guo/mmix/odernn/main.py", line 119, in run
    train(model)
  File "/home/guo/mmix/odernn/main.py", line 70, in train
    ret = model.run_on_batch(data, optimizer, epoch)
  File "/home/guo/mmix/odernn/models/brits.py", line 66, in run_on_batch
    ret = self(data, mode="train")
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/brits.py", line 24, in forward
    ret_f = self.rits_f(data, 'forward', mode)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/rits.py", line 51, in forward
    outputs = self.ode_rnn(inputs, m, m_first, time_steps)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/ode_rnn.py", line 202, in forward
    hidden = mask_first[:, i - 1] * hidden
RuntimeError: The size of tensor a (325) must match the size of tensor b (170) at non-singleton dimension 1
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
Traceback (most recent call last):
  File "/home/guo/mmix/odernn/main.py", line 124, in <module>
    run()
  File "/home/guo/mmix/odernn/main.py", line 119, in run
    train(model)
  File "/home/guo/mmix/odernn/main.py", line 70, in train
    ret = model.run_on_batch(data, optimizer, epoch)
  File "/home/guo/mmix/odernn/models/brits.py", line 66, in run_on_batch
    ret = self(data, mode="train")
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/brits.py", line 24, in forward
    ret_f = self.rits_f(data, 'forward', mode)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/rits.py", line 51, in forward
    outputs = self.ode_rnn(inputs, m, m_first, time_steps)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/ode_rnn.py", line 202, in forward
    hidden = mask_first[:, i - 1] * hidden
RuntimeError: The size of tensor a (323) must match the size of tensor b (170) at non-singleton dimension 1
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
Traceback (most recent call last):
  File "/home/guo/mmix/odernn/main.py", line 124, in <module>
    run()
  File "/home/guo/mmix/odernn/main.py", line 119, in run
    train(model)
  File "/home/guo/mmix/odernn/main.py", line 70, in train
    ret = model.run_on_batch(data, optimizer, epoch)
  File "/home/guo/mmix/odernn/models/brits.py", line 66, in run_on_batch
    ret = self(data, mode="train")
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/brits.py", line 24, in forward
    ret_f = self.rits_f(data, 'forward', mode)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/rits.py", line 51, in forward
    outputs = self.ode_rnn(inputs, m, m_first, time_steps)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/ode_rnn.py", line 202, in forward
    hidden = mask_first[:, i - 1] * hidden
RuntimeError: The size of tensor a (325) must match the size of tensor b (170) at non-singleton dimension 1
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
Traceback (most recent call last):
  File "/home/guo/mmix/odernn/main.py", line 124, in <module>
    run()
  File "/home/guo/mmix/odernn/main.py", line 119, in run
    train(model)
  File "/home/guo/mmix/odernn/main.py", line 70, in train
    ret = model.run_on_batch(data, optimizer, epoch)
  File "/home/guo/mmix/odernn/models/brits.py", line 66, in run_on_batch
    ret = self(data, mode="train")
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/brits.py", line 24, in forward
    ret_f = self.rits_f(data, 'forward', mode)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/rits.py", line 51, in forward
    outputs = self.ode_rnn(inputs, m, m_first, time_steps)
  File "/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guo/mmix/odernn/models/ode_rnn.py", line 202, in forward
    hidden = mask_first[:, i - 1] * hidden
RuntimeError: The size of tensor a (323) must match the size of tensor b (170) at non-singleton dimension 1
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torch/onnx/_internal/_beartype.py:30: UserWarning: unhashable type: 'list'
  warnings.warn(f"{e}")
/home/guo/anaconda3/envs/dual/lib/python3.9/site-packages/torchdiffeq/_impl/misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")
